Repository rivasbolinga/massage-caroline, pull requests merged in 2023-04, with the labels that each got.

#18 4 sophrology
  package-lock.json
  package.json
  public/index.html
  public/locales/fr/translation.json
  src/App.css
  src/App.js
  src/assets/icons/massage (1).png
  src/assets/icons/massage.png
  src/components/Bookings.jsx
  src/components/aboutPage/About.jsx
  src/components/features/footer/Footer.jsx
  src/components/features/home-sliders/SliderComponent.jsx
  src/components/features/navigation/Navigation.jsx
  src/components/features/navigation/NavigationMobile.jsx
  src/components/sophrology/Sophrology.jsx
  src/components/styles/About.scss
  src/components/styles/AboutPhone.scss
  src/components/styles/Sophrology.scss
  src/components/styles/common.scss
Labels: Component skelton, Styling Complete

#21 Home page improved and massages Redux State
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/customer.png
  src/assets/home-massage-pics/banner.png
  src/assets/home-massage-pics/massage-1.jpg
  src/assets/home-massage-pics/massage-2.jpg
  src/assets/home-massage-pics/massage-3.jpg
  src/assets/home-massage-pics/massage-4.jpg
  src/assets/home-massage-pics/massage-5.jpg
  src/assets/massage-banners/background-makups.jpg
  src/components/GiftCard.jsx
  src/components/Home.jsx
  src/components/Massages.jsx
  src/components/aboutPage/About.jsx
  src/components/aboutPage/AboutPhone.jsx
  src/components/features/home-carousel/Banner.jsx
  src/components/features/home-carousel/Carousel.jsx
  src/components/features/home-sliders/Feedback.jsx
  src/components/features/home-sliders/Gallery.jsx
  src/components/features/home-sliders/ProductCard.jsx
  src/components/features/home-sliders/SliderComponent.jsx
  src/components/features/home-sliders/styles.scss
  src/components/features/navigation/Navigation.jsx
  src/components/features/navigation/NavigationMobile.jsx
  src/components/redux/massages/massageSlice.js
  src/components/redux/store.js
  src/components/sophrology/Sophrology.jsx
  src/components/styles/About.scss
  src/components/styles/ButtonBookNow.jsx
  src/components/styles/HomeTitle.jsx
  src/components/styles/Sophrology.scss
  src/index.js
Labels: Component skelton, Funtionality Skelton

#32 2.1 home page massages
  src/assets/images/bc3.png
  src/assets/images/bc4.png
  src/assets/images/bc5.png
  src/assets/images/massage1.jpeg
  src/assets/images/massage2.jpeg
  src/assets/images/massage3.jpeg
  src/components/aboutPage/About.jsx
  src/components/aboutPage/AboutPhone.jsx
  src/components/features/home-sliders/ProductCard.jsx
  src/components/features/home-sliders/SliderComponent.jsx
  src/components/features/home-sliders/TranslatedTitle.jsx
  src/components/features/home-sliders/styles.scss
  src/components/redux/massages/massageSlice.js
  src/components/styles/HomeTitle.jsx
Labels: feedback

#44 About me
  src/App.js
  src/assets/bc-images/bc2.png
  src/assets/bc-images/bc3.png
  src/assets/bc-images/bc4.png
  src/assets/images/massage6.jpg
  src/components/Home.jsx
  src/components/aboutPage/About.jsx
  src/components/aboutPage/AboutPhone.jsx
  src/components/features/aboutImages/AboutImages.jsx
  src/components/sophrology/Sophrology.jsx
  src/components/styles/About.scss
  src/components/styles/AboutPhone.scss
  src/components/styles/Sophrology.scss
Labels: enhancement, Styling Complete
