Repository rivasbolinga/massage-caroline, pull requests merged in 2023-05, with the labels that each got.

#45 404 page && Translation
  public/background404.avif
  public/locales/en/translation.json
  public/locales/fr/translation.json
  public/massage-5.jpg
  src/App.js
  src/components/Default404.jsx
  src/components/contactpage/Contact.jsx
  src/components/contactpage/From.jsx
  src/components/features/footer/Footer.jsx
  src/components/features/home-carousel/CarouselWrap.jsx
  src/components/sophrology/Sophrology.jsx
  src/components/styles/Contact.scss
  src/index.css
Labels: enhancement, Component skelton, Styling Complete, compoonent complete

#47 9.2 navigation transitions
  public/massage-5.jpg
  src/App.js
  src/components/Bookings.jsx
  src/components/Sophrology.jsx
  src/components/features/footer/Footer.jsx
  src/components/features/home-sliders/FeedbackCard.jsx
  src/components/features/navigation/NavigationMobile.jsx
  src/components/styles/Navigation.scss
  src/components/styles/NavigationMobile.scss
Labels: enhancement

#48 Feedback from customer
  src/assets/customer-1.png
  src/assets/customer-2.png
  src/assets/customer-3.png
  src/assets/customer.png
  src/components/features/home-sliders/Feedback.jsx
Labels: enhancement, feedback

#50 Last feedback
  public/index.html
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/assets/bc-images/bc5.png
  src/assets/bc-images/bc6.png
  src/assets/bc-images/bc7.png
  src/assets/bc-images/bc8.png
  src/assets/bc-images/bc9.png
  src/components/Massages.jsx
  src/components/contactpage/Contact.jsx
  src/components/contactpage/From.jsx
  src/components/features/footer/Footer.jsx
  src/components/features/social/SocialLogos.jsx
  src/components/sophrology/Sophrology.jsx
  src/components/styles/About.scss
  src/components/styles/Contact.scss
  src/components/styles/Sophrology.scss
Labels: enhancement, feedback
